"""Level-0 classification: the labels that need no model at all.

Most job mail is machine-generated by a handful of senders that say the same
handful of things, and the model was being paid to rediscover that on every
message. Measured over the stored mailbox: 265 of the 312 messages that ended
up needing a human were job-board digests from five senders - LinkedIn job
alerts, Glassdoor, ZipRecruiter, Indeed match, Jobright - and the acknowledgement
vocabulary is almost a closed set ("thank you for applying", "we have received
your application", "your application was sent to").

So this runs first and answers the easy cases outright. Whatever it declines
goes to `pipeline/router.py` and costs a model call, which is now the exception
rather than the rule.

Two disciplines hold this together:

- **Decline rather than guess.** Returning None is free; a wrong confident label
  moves a job to the wrong list. "Thank you for your interest in X" is the
  clearest example - it opens acknowledgements *and* rejections in equal
  measure, so no rule here touches it and the model gets to read the body.
- **Order is the logic.** ATS relays (Greenhouse, Workday, Ashby) carry
  acknowledgements, updates, and their own marketing from the same address, and
  boards send acknowledgements as well as alerts. So subject intent is settled
  before sender reputation is consulted, and sender is only allowed to decide
  when the subject said nothing.

The email is untrusted third-party text, but nothing here executes it - these
are pattern matches over the subject and sender, with a fixed label set as the
only possible output. Bodies are not read: a digest listing ten roles contains
every phrase in this module, and matching against it would label alerts as
acknowledgements.
"""

import re

from utilities.mailstore import (
    CATEGORY_ACKNOWLEDGEMENT,
    CATEGORY_ALERT,
    CATEGORY_IRRELEVANT,
    CATEGORY_UPDATE,
)

#: Recorded in `messages.category_model` for a rule-assigned label, so a bad
#: label can be attributed to this module rather than blamed on a provider.
#: Same reason the column exists at all.
RULE_MODEL = "rules"

#: Rules see one line - "Sender Name <address@host>" plus the subject - and that
#: is deliberate. See the module docstring on why bodies are excluded.
_FLAGS = re.IGNORECASE


def _any(*patterns):
    """Compile alternatives into one pattern.

    Summary:
        Build a single case-insensitive regex matching any of the alternatives.

    Parameters:
        *patterns (str): Regex fragments to alternate between.

    Returns:
        re.Pattern: The compiled alternation.
    """
    return re.compile("|".join(f"(?:{p})" for p in patterns), _FLAGS)


# --- 1. Board and network noise ------------------------------------------
#
# Mail from a job board that advertises no role: product marketing, community
# digests, verification codes, event reminders. It reaches this stage because
# the rough filter passes every board domain unconditionally, and it used to be
# labelled `job_alert` on the strength of the sender - which put "Welcome to
# MyGreenhouse" in a queue asking which of the user's applications it belonged
# to.

BOARD_NOISE_SUBJECT = _any(
    r"^welcome to\b",
    r"\bdream job\b",
    r"\bget noticed by recruiters\b",
    r"\byou'?re attending\b",
    r"\byour .{0,20}\bsubscription\b",
    r"\bverification code\b",
    r"\bsecurity (?:code|alert)\b(?!.*\bapplication\b)",
    r"\b(?:confirm|verify) your email\b",
    r"\bpassword\b",
    r"\bwebinar\b",
    r"\bnewsletter\b",
    r"\breplied to your inmail\b",
    r"\bviewed your profile\b",
    r"\bprofile views?\b",
    r"\bwho'?s viewed\b",
    r"\bis now part of\b",
    r"\bthank you for purchasing\b",
    r"\bterms of (?:service|use)\b",
    r"\bprivacy policy\b",
    r"\bjust messaged you\b",
    # Board "insights" mail: salary and market chatter with no posting behind
    # it. "$100K/yr+ salary at 6.2K job openings" is not a role to apply to.
    r"\binsights?\b.*\bsalary\b",
)

#: Senders that are structurally not job postings even on a board domain.
#: LinkedIn is the reason this is keyed on the local part: one domain carries
#: alerts, InMail, newsletters, billing, and network noise, and only the first
#: is a job posting.
#:
#: `inmail-hit-reply@linkedin.com` is deliberately **absent**. It looked like
#: noise, but the stored mail says otherwise - it is how a human recruiter's
#: approach arrives, subject lines like "Open Job For Associate, Software
#: Engineer" included. Those are exactly the messages this pipeline exists to
#: not lose, so the address goes to the model instead.
NOISE_SENDERS = _any(
    r"newsletters-noreply@linkedin\.com",
    # Negative lookbehind so this does not also swallow `inmail-hit-reply@`,
    # which is a different address with the opposite meaning.
    r"(?<![\w.-])hit-reply@linkedin\.com",
    r"messages-noreply@linkedin\.com",
    r"messaging-digest-noreply@linkedin\.com",
    r"invitations?-noreply@linkedin\.com",
    r"updates-noreply@linkedin\.com",
    r"group-digests@linkedin\.com",
    r"billing-noreply@linkedin\.com",
    r"payments-noreply@linkedin\.com",
    r"support@ziprecruiter\.com",
    # Same address as the Glassdoor job alerts; only the display name separates
    # the forum digest from a real posting, so it is matched on that.
    r"glassdoor community",
)


# --- 2. Acknowledgements ---------------------------------------------------
#
# "We got it" and nothing more. The vocabulary is nearly closed, and every
# pattern here is anchored on the reader's *own* application - a phrase that a
# digest advertising other people's openings cannot produce.

ACKNOWLEDGEMENT_SUBJECT = _any(
    r"\bthank(?:s| you)\b.{0,30}\bfor applying\b",
    r"\bthank(?:s| you)\b.{0,30}\bfor your application\b",
    r"\bthank(?:s| you)\b.{0,30}\bfor submitting\b",
    r"\bthanks for your interest in applying\b",
    r"\bfor applying (?:to|at|with)\b",
    r"\bapplication (?:has been |was )?received\b",
    r"\bwe(?:'ve| have)? received your application\b",
    r"\breceived your application\b",
    # Not `your application is complete`: ZipRecruiter quotes the role between
    # the two words - `Your "Automated QA Engineer" application is complete` -
    # so the anchor has to be the tail of the phrase.
    r"\bapplication is complete\b",
    r"\byour application (?:is|was) (?:received|submitted)\b",
    r"\bapplication (?:confirmation|received|submitted)\b",
    r"\bconfirmation of your application\b",
    r"\byour recent (?:job )?application\b",
    r"\bkeep track of your application\b",
    # LinkedIn Easy Apply's receipt. Sent from the same address as its alerts,
    # which is why subject intent is settled before sender reputation.
    r"\byour application was sent to\b",
    r"\bthanks for submitting your application\b",
    r"\bthanks? you for your recent application\b",
)


# --- 3. Updates ------------------------------------------------------------
#
# News about something already submitted. Every pattern is deliberately
# multi-word: a bare "interview" or "offer" appears in board digests
# ("Interview Coach at Google", "Offer Management Analyst"), and matching those
# would attach an advert to an application and mark the wrong job dead.

UPDATE_SUBJECT = _any(
    r"\bupdate on your\b.{0,30}\bapplication\b",
    r"\bapplication (?:status|update)\b",
    r"\bstatus (?:update|of your application)\b",
    r"\byour application (?:to|for|with)\b.{0,60}\b(?:update|status|decision)\b",
    # LinkedIn's status mail: "Your application to <role> at <company>". The
    # acknowledgement rules run first, so its "your application was sent to"
    # receipt is already claimed and cannot reach this.
    r"^your application (?:to|for)\b",
    r"\binterview (?:invitation|invite|request|confirmation|reminder|scheduled|availability)\b",
    r"\b(?:invitation|invite|request) (?:to|for) (?:an? )?interview\b",
    r"\bschedule (?:an? |your )?interview\b",
    # "Next steps" needs an application nearby to count. On its own it belongs
    # to course reminders and marketing as often as to a hiring pipeline.
    r"\bapplication\b.{0,40}\bnext steps?\b",
    r"\bnext steps?\b.{0,40}\b(?:application|interview|candidacy|hiring)\b",
    r"\bonline assessment\b",
    r"\b(?:coding|technical) (?:assessment|challenge|screen)\b",
    r"\bassessment (?:invitation|invite|is ready|link)\b",
    r"\bmoving forward\b",
    r"\bnot (?:be )?(?:moving|proceeding) forward\b",
    r"\bno longer under consideration\b",
    r"\bregarding your application\b",
    r"\b(?:offer|employment) letter\b",
    r"\boffer of employment\b",
    r"\bwithdrawal notice\b",
    r"\bsecurity code for your application\b",
    r"\bverify your identity for\b",
)


# --- 4. Alerts -------------------------------------------------------------
#
# Reached only once the subject has been shown to carry no application intent.

#: Addresses that send nothing but job digests. Matched on the full address
#: rather than the domain: `jobalerts-noreply@linkedin.com` is always an alert
#: while `jobs-noreply@linkedin.com` also sends Easy Apply receipts, and
#: collapsing the two loses that.
ALERT_SENDERS = _any(
    r"jobalerts-noreply@linkedin\.com",
    r"jobs-listings?@linkedin\.com",
    r"jobposting.*@linkedin\.com",
    r"@match\.indeed\.com",
    r"alert.*@indeed\.com",
    r"invitetoapply@indeed\.com",
    r"alerts@ziprecruiter\.com",
    r"jobs@ziprecruiter\.com",
    # `noreply@` only. Jobright also mails from `support@`, which mixes real
    # digests with product marketing, so that address is left to the subject
    # rules and, failing those, to the model.
    r"noreply@jobright\.ai",
    r"alerts@jobright\.ai",
    r"noreply@glassdoor\.com",
    r"jobs-noreply@linkedin\.com",
    r"@mail\.jobcase\.com",
    r"@dice\.com",
    r"@monster\.com",
    r"@simplyhired\.com",
    r"@talent\.com",
    r"@wellfound\.com",
)

#: Digest phrasing, usable regardless of sender. This is what catches the
#: long tail - a company careers list or a niche newsletter that advertises
#: roles but is on no list anyone maintains.
ALERT_SUBJECT = _any(
    r"\b\d+\s+(?:new\s+)?(?:jobs?|roles?|openings?|matches)\b",
    r"\bnew jobs?\b",
    r"\bmatching jobs?\b",
    r"\bmay want to hire you\b",
    r"\bjob alert\b",
    r"\bjobs? (?:for|near) you\b",
    r"\bjobs? you might (?:like|be interested)\b",
    r"\band \d+ more jobs?\b",
    r"\b\d+%\s*match\b",
    r"\brecommended .{0,20}jobs?\b",
    r"\byour job matches\b",
    r"\bjob matches for\b",
    r"\bmight be right for you\b",
    r"\bapply now to\b",
    r"\bis hiring (?:now|for)\b",
    r"\bhas an open position\b",
    r"\bjust posted\b",
    r"\bnew (?:opportunit|role|position)\w*\s+(?:for|at|near)\b",
    r"\bwould be a great fit\b",
    r"\bhiring (?:now|near you)\b",
    r"\broles? for you\b",
    r"\byour daily\b.{0,20}\bjobs?\b",
    r"\bopen (?:roles?|positions?)\b",
)

def classify(sender, subject):
    """Label a message from its headers, or decline.

    Summary:
        Apply the deterministic rules to one message's sender and subject.

    Parameters:
        sender (str): The raw From header, name and address together.
        subject (str): The subject line.

    Returns:
        dict | None: `{"label", "confidence", "reason"}` when a rule fires, and
            None when none does - which means the caller should ask the model.

    Note:
        Rule order is the logic, not a style choice. Noise is excluded first,
        then subjects that speak about the reader's own application, and only
        then the sender's reputation as a board. Reversing the last two would
        label LinkedIn's "your application was sent to X" as an advert.
    """
    sender = (sender or "").strip()
    subject = (subject or "").strip()
    if not sender and not subject:
        return None

    if NOISE_SENDERS.search(sender) or BOARD_NOISE_SUBJECT.search(subject):
        return {
            "label": CATEGORY_IRRELEVANT,
            "confidence": 0.95,
            "reason": "Board or network mail that advertises no role.",
        }

    # Before the sender tiers: a board is perfectly capable of sending a
    # receipt, and the subject is the only thing that says so.
    if ACKNOWLEDGEMENT_SUBJECT.search(subject):
        return {
            "label": CATEGORY_ACKNOWLEDGEMENT,
            "confidence": 0.95,
            "reason": "Subject confirms an application was received.",
        }

    if UPDATE_SUBJECT.search(subject):
        return {
            "label": CATEGORY_UPDATE,
            "confidence": 0.9,
            "reason": "Subject carries news about a submitted application.",
        }

    if ALERT_SENDERS.search(sender):
        return {
            "label": CATEGORY_ALERT,
            "confidence": 0.95,
            "reason": "Sender is a job board's alert address.",
        }

    if ALERT_SUBJECT.search(subject):
        return {
            "label": CATEGORY_ALERT,
            "confidence": 0.9,
            "reason": "Subject advertises one or more openings.",
        }

    # A tier that labelled anything from a board domain as an alert used to sit
    # here. It was measured and removed: it fired only after every specific rule
    # had declined, and by then what was left was "Terms of Service Updates" and
    # "Thank you for purchasing Premium" - it produced four of the five real
    # errors in the whole backtest and caught nothing the rules above missed.
    return None


def classify_message(message):
    """Label a stored message row, or decline.

    Summary:
        Adapt a mailbox row to `classify`.

    Parameters:
        message (Mapping): A row or dict carrying `sender` and `subject`.

    Returns:
        dict | None: As `classify`.

    Note:
        Reads by subscript rather than `.get`, because the callers pass both
        plain dicts and `sqlite3.Row` - and a Row has no `.get`. The docstring
        said "row or dict" long before that was true of the code.
    """
    return classify(_field(message, "sender"), _field(message, "subject"))


def _field(message, name):
    """One field of a row or dict, or None when absent.

    Summary:
        Read a named field from either mapping type.

    Parameters:
        message (Mapping | sqlite3.Row): The message to read.
        name (str): The field name.

    Returns:
        str | None: The value, or None when the field is missing.
    """
    try:
        return message[name]
    except (IndexError, KeyError):
        return None
